[build]
  command = "npm run build"
  publish = "build"

[context.deploy-preview]
  command = "npm run build-preview"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

client_id: { 221380827665-s1fh9lqjp1tgns0skn8bgh1nmikln0e5.apps.googleusercontent.com }